# Generated by Django 5.0.7 on 2024-07-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='Himel.jpg', upload_to='media/images')),
                ('is_available', models.BooleanField()),
                ('price', models.IntegerField()),
                ('size', models.FloatField()),
                ('property_type', models.CharField(choices=[('flat', 'Flat'), ('house', 'House')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
