# Generated by Django 5.0.7 on 2024-08-02 15:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('options', multiselectfield.db.fields.MultiSelectField(choices=[('option1', 'Option1'), ('option2', 'Option2'), ('option3', 'Option3')], max_length=23)),
            ],
        ),
    ]
